<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{93197c60-806b-4e15-b6d1-f529f30b5b27}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL_HMI.hmiPanel();

UpperPreserDrive();
HydraulicPump();
BreakthroughDetection_2();



P_Events();
P_EventsDefinition();
Alarms();
Scaling();
SavePresistent();
Mode();
IO_Map();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="37" Count="10" />
      <LineId Id="22" Count="0" />
      <LineId Id="48" Count="1" />
      <LineId Id="53" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>