<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="Alarmy" Id="{8cd91d19-e7e8-47aa-8be1-a23412e084d2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Alarmy
VAR
	Migacz: FB_Blink_S;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
Migacz(Tv:=T#500MS , Q=> );]]></ST>
    </Implementation>
    <LineIds Name="Alarmy">
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>